### ISSUE TITLE
Add command parameter metadata

### ISSUE THREAD

**Issue by jurentie** [OpenWaterFoundation/owf-app-geoprocessor-python#224]
From Steve:
"I really hope that you can get the command input properties working.  In order to have the most impact for testing framework at TriLynx and Kristin's work, I think you should focus on the following commands in approximate order of importance:

- [x] StartLog
- [x] RemoveFile
- [x] RunProgram
- [x] CompareFiles
- [x] CreateRegressionTestCommandFile
- [x] WebGet
- [x] Message
- [x] ReadGeoLayerFromGeoJSON
- [x] ReadGeoLayerFromShapefile

**Comment by smalers** [comment]
Here is my feedback.

`StartLog`

- I edited the properties.
- [ ] Command description does not need to repeat the command name since it is shown in the dialog title.
- [ ] Why is `LogFile.Values` a property?  It is not needed.
- [ ] In general, the `DefaultValue` might be able to default based on input type.  For example, if a text field or a combo box (choice) that includes an empty string.
- [ ] All file input needs an ***Abs*** button like TSTool to convert to-from relative and absolute path.  See TSTool.  Absolute paths are not needed that often but are useful to toggle back and forth to see where a file really lives.  If necessary, leave it out for now but plan to put back in.  A property may also be needed to show this like `FileSelector.IncludeAbs`.
- [ ] Need a property `xxx.FileSelector.Title` to set the title on the file selector so that once the file selector dialog is open the title can remind the user what they are doing such as `Select Log File`.
- [ ] The file selector needs to open in a folder relative to the working folder if it contains an existing value that is a relative path.  See the `io_util` functions `to_relative_path`, `to_absolute_path` and also `verify_path_for_os`.  See the `run_command` method for how used.  Going forward, we may need to standardize on Linux-like paths so that people can collaborate on command files on Windows and Linux without flip-flopping paths in the command file (and repos).
 - [ ] In general recommend using period to separate sub-properties like the above example, so change `FileSelectorType` to `FileSelector.Type`.
- [ ] The labels to the left of input components should line up and the left edge of components should line up.  This gives a nice alignment.

`RemoveFile`

- [ ] `SourceFile.Label` does not seem to be recognized?  The parameter name is being used.  Same for other parameters?
- [ ] I added a blank string in `Values`.  A blank should not always be added automatically because some parameters won't allow a blank choice.  I recommend adding a standard property `DefaultDisplayValue` that is the value shown in the UI.  This is particularly important for choices where a default display value may be empty string and the value used in that case will be the `DefaultValue`.  Maybe have some logic like if the `DefaultDisplayValue` is not in `Values` it will be added at the front.  If it is found, don't add again.  Also, need to make sure choices don't have any redundant values that accidentally get added.
- [ ] The button to select file needs to not take up the whole parameter description space so that the filename text field can be wider.  This can be done by setting the layout width of the description to multiple columns.

`RunProgram`

- [ ] If a parameter is required, there should be no `(default=...)` at the end of the parameter description.

**Comment by jurentie** [comment]
I've successfully added the minimum functionality to the simple command editors for the commands listed above. Next is to clean up any code or layout issues...

**Comment by smalers** [comment]
I ran into major issues in reviewing the command editor code.  I sent an email to Justin and will need to have a discussion to resolve.
