### ISSUE TITLE
Need a GeoProcessor class property to hold the QGIS version information 

### ISSUE THREAD

**Issue by egiles16** [OpenWaterFoundation/owf-app-geoprocessor-python#48]
As the QGIS version is updated, the API functionality and syntax changes. The `GeoProcessor` needs to be aware of the deployed environment's QGIS version so that the corresponding `GeoProcessor` code can be run. 

Emma has added the following 3 QGIS utility functions to obtain information about the installed QGIS version:

1. `get_qgis_version_int `: returns the QGIS version (in integer format) 
```
ex: 21809
```

2. `get_qgis_version_name`: returns the name of the QGIS version 
```
ex: Las Palmas
```

3. `get_qgis_version_str`: returns the QGIS version (in string format) 
```
ex: 2.18.9
```

Resource: [Python- QGIS Version Information - Stack Overflow](https://stackoverflow.com/questions/26239144/python-qgis-version-information)

Needs Steve input on how to use the above util functions to get the information within GeoProcessor properties.

**Comment by smalers** [comment]
The version is shown in the software properties.  Need to add as a processor property like the working directory.

**Comment by smalers** [comment]
The `ProgramVersionString`, `ProgramVersionDate`, and `ProgramVersionNumber` are shown in the processor properties and are now populated.  I also moved the QGIS version code to the new `qgis_version_util.py` file so that the version can be checked in a minimalist way to wrap `import` statements.  Close this issue.
