### ISSUE TITLE
Review and refactor command editor design.

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-geoprocessor-python#68]
A basic design for command editor is in place for ReadGeoLayerFromGeoJSON command.  The design needs to be reviewed and refactored to make sure it can be scaled to all commands.

**Comment by jurentie** [comment]
The majority of these issues have been taken care of in updating all commands. There will still be a need to develop a `TabbedCommandEditor` class, but for now I will close out this issue and may create separate issues moving forward for any unfinished business.

Some comments on the above:
 * There are now two implemented command editors to fit different needs for the command. 1.) `GenericCommandEditor` - used as a default for all commands. (**not currently scrollable**) 2.) `SimpleCommandEditor` - Allows for drop down menus, tooltips, descriptions, and file selectors to allow more flexibility for configuring more complicated commands. 
* More resusable code can now be found in `AbstractCommandEditor`
* Properties have been added for each parameter in the command files. 
Ex:
 ```
# Command Parameter Metadata
        self.parameter_input_metadata = dict()
        # DelimitedFile
        self.parameter_input_metadata['DelimitedFile.Description'] = "the delimited file to read"
        self.parameter_input_metadata['DelimitedFile.Label'] = "Delimited File"
        self.parameter_input_metadata['DelimitedFile.Required'] = True
        self.parameter_input_metadata['DelimitedFile.Tooltip'] = "The delimited file to read (relative or absolute " \
            "path). ${Property} syntax is recognized."
        self.parameter_input_metadata['DelimitedFile.FileSelector.Type'] = "Read"
        self.parameter_input_metadata['DelimitedFile.FileSelector.Title'] = "Select a delimited file to read."
```
* TSTool design of editing a command and adding it to the command list (after being checked for validity) has been implement. It is implemented in a slightly different way than TSTool but ultimately follows the same logic. **We need to find a way to copy the command instead of manipulating it directly when editing a command**.
